### ISSUE TITLE
Reset new_id when the game starts

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#177]
The "new_id" function makes sure every tile gets an id. But when the game is reset, "new_id" doesn't reset. This makes it so when the game starts again, the tiles get an id higher than 1, and this can cause issues with the for loops or further features.

Make sure the new_id function reset when the gamestate "playing" is loaded.

**Comment by richelbilderbeek** [comment]
I enjoy the thought put in this Issue, but I will close it nevertheless :rainbow:  

The reason is that an ID is now coded as an integer. These have 2 billion positive values. As long as we don't create 2 billion tiles in the run of a game, there will be no problem. I predict this will never happen. If I am wrong, I will re-open this Issue :+1:
