### ISSUE TITLE
Suggest which game we'll make before Tuesday 11th 18:00

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#2]
Put your game suggestions at this topic. The suggestions must satisfy these constraints:

 * Platform: desktop
 * 2D (not isometric, not 3D)
 * Single or one-screen multiplayer (not an online game)
 * Desktop application (not a network/NDS/mobile/web application)
 * Single-screen (not scrolling)
 * Graphics: either generated or downloaded sprites (no drawing of sprites)
 * Genre: any genre: horror, shooter, RPG, adventure, visual novel, strategy, puzzle, platformer

**Comment by richelbilderbeek** [comment]
At Tuesday September 11th night, I will place all suggestions that I think are realistic to #3 for majority voting. Then I will close this Issue.

**Comment by Joshua260403** [comment]
Open world survival game with tile system (walking of screen > switch world tile). Hunger, thirst and health, enemies and animals, weapons and tools, building, exploring, and the ability to create and download mods. "Flatworld"

**Comment by RafayelGardishyan** [comment]
![Image of the prototype](https://github.com/richelbilderbeek/djog_unos_2018/raw/master/pics/IMG_20180907_215839.jpg)

# Nature Zen

A game which consists of tiles that look like coth. (See picture.)
In this game, the different patterns on the cloth represent different types of worlds, such as forests, cities, oceans, rivers, mountains.

### Main Features 
- The player can move these tiles to alter the world and the creatures who live on it.e 
- The player can interact with the creatures, for example, kill them, send them to a different location etc.
- On the bottom of the world, there is a 'dark side' and the player can turn each tile over to reveal the dark side and maybe harm the creatures on top in some way.
- The world's amount of tiles is finite but gradually increasing, the empty places consist of an endless pit the creatures can fall in. (A finite amount of tiles is handy to make it less complicated for the player to move the tiles.)

### Extra Features
- The player can zoom in on a tile and see more tiles on that tile
- Create enemies: People (Because the game is about the "Nature Zen")
- More detailed worlds with planets etc.
- Draw graphics

### Credits
Idea by:
- Rafayel Gardishyan
- Anne Hinrichs
- A little bit by Joshua van Waardenberg and Richel Bilderbeek

###### More ideas are welcome in the comments

**Comment by Joshua260403** [comment]
Mini metro but better :)

**Comment by same-drenth** [comment]
[https://en.wikipedia.org/wiki/This_War_of_Mine](url) for info about the game. 
[https://www.digiseller.ru/preview/595578/p1_2234325_c76e4222.jpg](url) for an example of the perspective.

**Comment by richelbilderbeek** [comment]
Deadline! No more suggestions here anymore. Will close Issue after moving suggestions to #3

**Comment by richelbilderbeek** [comment]
Vote at #3 , closing this Issue.
