### ISSUE TITLE
Add functions 'is_on_tile(game, x, y)' and is_on_tile(game, agent)

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#261]
**Is your feature request related to a problem? Please describe.**

Currently, we have no way to easily measure if a coordinat and/or agent is on a tile or not.

**Describe the solution you'd like**

Add two functions:

```
bool is_on_tile(const game& g, const double x, const double y);
bool is_on_tile(const game& g, const agent& a);
```

The second function should call the first one.

Write tests for both functions: one if the coordinat/agent is on a tile, and one if it is not.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Game.cpp line 106

**Comment by Joshua260403** [comment]
I have a couple of questions here,
1. How is it supposed to work if the only thing it can return is true
2. Why was this in done

**Comment by Joshua260403** [comment]
(Continuing from #286 ) Seeing some issues @robkruger has done (#286 #288 and this one) makes me believe @robkruger is a bit hasty. This isn't always a bad thing, the faster an issue is done, the earlier we can move on to the next step. However, looking back at #110, and seeing the result of his work, i think it's a bit too fast. a couple of his issues aren't even really done, and that results in him having alot of issues to do (of course we could assign someone else, that's what i'm getting to). So that's why i advice @robkruger to take his time. It doesn't matter if you don't do alot of issues, and seeing the skill @robkruger has, i think he should consider doing some bigger issues. That way the not as skilled members of team octane can get an issue that is more at their level. Also, he should take a bit more time to look closely at what he's doing, because like i said, some issues aren't really finished. Wow i can write long messages. Keep up the good work @robkruger :+1:

**Comment by richelbilderbeek** [comment]
I agree with the well-written analysis of @Joshua260403. Time for @robkruger to move to bigger things :+1:

**Comment by richelbilderbeek** [comment]
To fix this Issue, fix this test:

```c++
  //#define FIX_ISSUE_261
  #ifdef FIX_ISSUE_261
  //'is_in_tile' should detect if there is a tile at a certain coordinat
  //positive control
  {
    //Tile at (0.0, 0.0, 0.0) with width and height of 10.0
    const std::vector<tile> tiles = { tile(0.0, 0.0, 0.0, 10.0, 10.0) };
    const std::vector<agent> no_agents;
    const game g(tiles, no_agents);
    //Coordinat (1.0, 1.0) is on a tile
    assert(is_on_tile(g, 1.0, 1.0));
    //Coordinat (-100.0, -100.0) is not on a tile
    assert(!is_on_tile(g, -100.0, -100.0));
  }
```

**Comment by Joshua260403** [comment]
Not only that, the function itself is currently a stub.

Op vr 11 jan. 2019 17:38 schreef Richel Bilderbeek <notifications@github.com
:

**Comment by Joshua260403** [comment]
check!
