### ISSUE TITLE
Water should be darker when depth is higher

### ISSUE THREAD

**Issue by robkruger** [richelbilderbeek/djog_unos_2018#286]
### Issue Description
Describe here what the issue is

The water tile should become dark blue when it's deep and light blue when it isn't and something in between.

**Comment by Joshua260403** [comment]
And i was right, appveyor failed as soon as i merged with develop. The variable color doesn't exist. Typing the word color instead of the blue value won't work...

**Comment by Joshua260403** [comment]
That's temporary: to help you on the way and to get develop working.
Improvements can be made by tweaking some things in the same line where i did my fix;

**Comment by Joshua260403** [comment]
I assigned myself to remember to reopen this if the commit saying it fixed this issue reaches master

**Comment by Joshua260403** [comment]
This is broken because @richelbilderbeek removed the variable declerations. He did that with a reason though. Because @robkruger is doing so many issues, part of the work of one issue came to develop with the finished work of the others. The work that was done for this issue caused OClint to say the variables were unused (because they were at the moment, OClint is always right). So when @robkruger got the rest of his work merged with develop, which i did because his branch was working, the first part of this was gone, causing develop to fail again. This story continues on issue #261
