### ISSUE TITLE
Working together comes first

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#386]
@robkruger: I am sorry to make this impopular decision, but the Team observed 

 * that you did a lot of work on your own branch (which is cool :+1:)
 * that you assigned yourself a lot of Issues (sorry, not a good idea)
 * that you did not merge `develop` to your branch, ultimately re-doing the work already done, causing useless merge conflicts

I enjoy the enthusiasm and I see and hear from others that you do good work, but you forgot the rest of the team. In the end, we had to decide to maintain `develop` (that had most Issues already fixed) and rejecting your merge to `develop`. It's not fun for me to decide, but well, it is for the best :rainbow: 

Easiest would be to delete your branch (sorry!) and re-create it from develop. It is not fun to throw away work, but I think you had a good time fixing the Issues, and it definitely shows your skills :sunrise_over_mountains: !

Now:

 * delete the `rob` branch, re-create it

Next time:

 * merge `develop` to your branch more often
 * read Issues, including the text below

If you have any questions, go ahead and post these here, or send me an email to richel@richelbilderbeek.nl .

**Comment by robkruger** [comment]
That's weird, because I checked multiple times if I was up to date with develop, even yesterday around 18:00. On the assign thing, I assigned myself a new issue when I was done with the other, so I don't see a problem with that? 

(Btw if I do `git checkout develop` and after that `git pull` and it says already up to date, it means that i'm up to date with develop and don't have to merge right?)

**Comment by richelbilderbeek** [comment]
Weird. Perhaps you use GitHub Desktop? We know that it can cause problems. Or perhaps something else is wrong. I suggest I take a look tonight :+1: 

@Joshua260403: I suggest I check Rob's setup tonight, so we can find out why this went sideways

**Comment by Joshua260403** [comment]
The problem was mainly the other way, Rob had too many additions on his branch that the rest wasn't up to date with. Also some issues Rob did weren't done correctly, causing issues for others who didn't have his changes and well, being incorrect. And one last thing, Rob did quite alot of issues, leaving no issues for other (which is part of the reason for the stress for me yesterday).

**Comment by robkruger** [comment]
OK! I'll do less issue's. I didn't have much to do this week, so that's why I did many this week. Which issue's weren't done correctly?

**Comment by richelbilderbeek** [comment]
Well, it is more nuanced than that: you did the Issues correctly, but did not merge your work to develop (spoiler: we will promote you to medior next week, so you can do that!), which caused the Issues to be done twice and merging would result in a lot of merge conflicts.

Your branch is now corrected, so you can do any Issue you like. We'll merge to develop next week together :+1:

Enjoy :rainbow:

**Comment by richelbilderbeek** [comment]
Note has served its purpose, closing it :+1:
