### ISSUE TITLE
Window manager does not open up a window

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#606]
PROBLEM:
The current code is building fine, but the program crashes hard due to a segmentation fault.
I tried fixing it, but due to lack of experience in snooping out and fixing segfaults and in handling the debugger in Qt Creator, I'm a my wits end.

SOLUTION:
Somehow search and fix the segmentation fault(s) that make the program crash.

**Comment by richelbilderbeek** [comment]
OK, I'll take a pass at it :+1:

**Comment by richelbilderbeek** [comment]
Found the bug. It is in the window manager. I've marked it as such:

```c++
  //#define FIX_ISSUE_606
  #ifdef FIX_ISSUE_606
  //A window should have opened up now
  assert(sfml_window_manager::get().get_window().isOpen()); //BUG: Issue #606
  #endif // FIX_ISSUE_606
```

@Joshua260403: I think you are best to fix this one  :1st_place_medal: :+1: 

I've put it on `develop`.

Yep, I've added some `std::clog` statements. Old-skool, but effective in finding bugs. You can let a junior delete these :+1:

**Comment by Joshua260403** [comment]
Hate to bring it to ya, but your hypothesis was wrong. The assertion passes on my system. The problem was that someone decided it was a good idea to write and activate a test for the not working loading screen. Ran with debugger once, segfault pointing me right at the loading screen. The clogs didn't work because none of them flushed. std::endl is superior after all

**Comment by janderkkotlarski** [comment]
So I was wrong in assuming it was funstions changing one of the vectors of agents or tiles causing the bug and right in giving up...
