### ISSUE TITLE
*.ogg is on the .gitignore list, why?

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#632]
I think with that on the gitignore file, adding ogg files and thus the tracks for the game is impossible for me.
Why is it on there?
Is it ok to remove the line, because it makes adding music file impossible?

**Comment by richelbilderbeek** [comment]
The reason is as follows: the `.ogg` files reside in the `resources` folder and are re-created locally when starting Nature Zen. If Nature Zen is run from its own folder (`djog_unos_2018`) it will re-create the `.ogg`s there. These duplicated `.ogg`s should be ignored.

The option I always use:

```
git add --force my.ogg
```


Does that help?

**Comment by janderkkotlarski** [comment]
Ok, I understand now, I didn't know that you could force an add through the gitignore
